Translate to spanish
trigaten/Learn_Prompting pull request #591
Opened 2023-04-06 18:14 UTC by AlanCienega

translate basics/formalizing.md and spelling correction

2023-04-06 18:47 UTC, dr-nefardio3058 requested changes
Hola. En esta review te dejo sugerencias sobre errores de ortografía para que las puedas incluir y corregir más rápido.

Buena contribución a pesar de los pequeños errores. 

![2295-catpetting](https://user-images.githubusercontent.com/124001513/230467873-747b280f-d6f3-4235-a2e3-68b8f423fec0.gif)

2023-04-06 18:47 UTC, dr-nefardio3058 commented on i18n/es/docusaurus-plugin-content-docs/current/basics/formalizing.md
> +There are a few different parts of a prompt that you will see over and over again. They are roughly:
```suggestion

```

Te olvidaste de sacar eso, está en ingles

2023-04-06 18:47 UTC, dr-nefardio3058 commented on i18n/es/docusaurus-plugin-content-docs/current/tooling/IDEs/langchain.md
> +[LangChain](https://github.com/hwchase17/langchain/) es una biblioteca de Python que proporciona varias funcionalidades para construir y encadenar promptps.
```suggestion
[LangChain](https://github.com/hwchase17/langchain/) es una biblioteca de Python que proporciona varias funcionalidades para construir y encadenar prompts.
```
Error de ortografía

2023-04-06 18:47 UTC, dr-nefardio3058 commented on i18n/es/docusaurus-plugin-content-docs/current/prompt_hacking/defensive_measures.md
> +La defensa en sandwich, cuyo descubrimiento actualmente le atribuyo a [Altryne](https://twitter.com/altryne?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor), implica intercalar la entrada del
```suggestion
La defensa en sandwich, cuyo descubrimiento actualmente le atribuyo a [Altryne](https://twitter.com/altryne?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor), implica intercalar la entrada del usuario entre dos prompts. Por ejemplo, `Traduce lo siguiente al francés: {{user_input}}` se convierte en:
```

Plural

2023-04-06 18:47 UTC, dr-nefardio3058 commented on i18n/es/docusaurus-plugin-content-docs/current/prompt_hacking/defensive_measures.md
> +Se puede usar un LLM (modelo de lenguaje grande) separado para juzgar si un prompt es adversario. Aquí hay un ejemplo de un prompt para dicho sistema (@armstrong2022using)). Fue bastante exitoso en l
```suggestion
Se puede usar un LLM (modelo de lenguaje grande) separado para juzgar si un prompt es adversario. Aquí hay un ejemplo de un prompt para dicho sistema (@armstrong2022using)). Fue bastante exitoso en la detección de prompts adversarios.
```

_Pequeño error_

2023-04-06 18:47 UTC, dr-nefardio3058 commented on i18n/es/docusaurus-plugin-content-docs/current/basics/formalizing.md
> +## Few Shot Standard Prompts
H1 en inglés

2023-04-06 18:47 UTC, dr-nefardio3058 commented on i18n/es/docusaurus-plugin-content-docs/current/prompt_hacking/defensive_measures.md
>  ## Defensa en sandwich
```suggestion
## Defensa en sándwich
```

2023-04-07 13:32 UTC, trigaten commented
Please resolve the merge conflict

2023-04-08 01:11 UTC, closed without merging